name: Pipeline skymed token generator
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pipe:
    runs-on: ubuntu-latest

    steps:
    - name: SSH Command
      uses: D3rHase/ssh-command-action@v0.2.1
      with:
        HOST: ${{secrets.SSH_HOST}}
        USER: ${{secrets.SSH_USER}}
        PRIVATE_SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        COMMAND: |
          cd applications
          rm -rf skymed_token_generator 
          git clone git@github.com:luisdevelopment/skymed_token_generator.git
          cd skymed_token_generator
          docker-compose up -d
